-- 시드는 별도 SQL이 필요 없습니다.
-- 앱이 Supabase에 처음 연결될 때 events 테이블이 비어 있으면
-- 데모 데이터(2026-07-04 토 / 2026-06-07 일 + 참가자 명단 + 예시 메모)를 자동 삽입합니다.
-- (lib/data/supabase-store.ts 의 auto-seed) — 좌석 좌표/카탈로그는 앱 상수(lib/venue)라 DB에 두지 않습니다.
--
-- 깨끗이 초기화하려면 Supabase SQL Editor에서:
--   truncate notes, draws, sellers, events cascade;
-- 실행 후 앱을 새로고침하면 데모 데이터가 다시 시드됩니다.
